import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load the scientific dataset generated by your bash script
df = pd.read_csv('lab2_dataset.csv')

# Separate data structures
contended = df[df['Data_Type'] == 'Contended']['Seconds'].values
isolated = df[df['Data_Type'] == 'Isolated']['Seconds'].values

# Establish plot frame
plt.figure(figsize=(10, 6))

# Generate a comparative bar chart for the 10 iterations
x = np.arange(1, 11)
width = 0.35

plt.bar(x - width/2, contended, width, label='Contended SPSC (False Sharing)', color='#e74c3c', alpha=0.85)
plt.bar(x + width/2, isolated, width, label='Isolated SPSC (alignas(64))', color='#2ecc71', alpha=0.85)

# Calculate and plot mathematical averages as horizontal trendlines
plt.axhline(y=np.mean(contended), color='#c0392b', linestyle='--', linewidth=1.5, label=f'Contended Avg ({np.mean(contended):.4f}s)')
plt.axhline(y=np.mean(isolated), color='#27ae60', linestyle='--', linewidth=1.5, label=f'Isolated Avg ({np.mean(isolated):.4f}s)')

# Scientific Chart Formatting
plt.title('SPSC Lock-Free Queue: Cache Line Contention vs. Hardware Isolation\n(50 Million Data Operations on Intel i5-4200U)', fontsize=12, fontweight='bold', pad=15)
plt.xlabel('Iteration Run Index', fontsize=11)
plt.ylabel('Total Execution Time (Seconds) - Lower is Better', fontsize=11)
plt.xticks(x)
plt.grid(axis='y', linestyle=':', alpha=0.6)
plt.legend(loc='upper right', framealpha=0.9)

# Save the visualization to disk
plt.savefig('lab2_performance_distribution.png', dpi=300, bbox_inches='tight')
print("[SCIENCE INFO] Visualization compiled successfully as 'lab2_performance_distribution.png'")

